main: io.github.spikey84.spikeymanhunt.spikeymanhunt
name: SpikeyManhunt
version: 1.1
commands:
    target:
      Description: Sets you as the tracker target.
      usage: /target [Player]
    compass:
      Description: Gives another tracking compass.
      usage: /compass [Player]
